log :
  path : "D:/Sherine Davis/Code/PycharmProjects/ShopifyInternshipApplication/logDump"
download :
  path : "D:/Sherine Davis/Code/PycharmProjects/ShopifyInternshipApplication/download"
service :
  port : 9086
database :
  type : mysql
  endpoint : abcdd.com
  port : 3306
  user : xyz
  password : ShopifyTest1
  name : shopify_db